### ISSUE TITLE
Not seeing card details in payment

### ISSUE THREAD

**Issue by delanick** [MohammedBashiru/rave-nativescript#1]
Hi there @MohammedBashiru ,

Thanks for this plugin, looks good!

Just need to know: your demo gif screenshots show capturing of credit card details and mobile network, yet in the code of your example and in demo example you don't capture or verify them anywhere. Please advise. Documentation isn't clear enough.

**Comment by MohammedBashiru** [comment]
Hello @delanick  if you want to accept card payment make sure to include `acceptCardPayments: true,` property to the context.

If you meant to capture the entered credit card details? That is being done by `Rave`. you can't capture credit card information or verify them your self.
